### ISSUE TITLE
More Tables?

### ISSUE THREAD

**Issue by jp-braun** [uwasystemhealth/FRACAS_Team1#28]
Do we need a few more small tables for to populate some drop-downs? Car year for example. Potentially status if it is an enum?

**Comment by VictorAZ12** [comment]
Since all records are available for all users to read&learn:
- For those fields that may have new values (like car year/nickname), we could simply return all unique values of a specific field within the database and also allow the user to input a new one. If a user inputs a wrong value by mistake, the user can always modify it later.
- For those fields that may have new values but cannot be added manually by normal users (permission-based fields like team, subsystem, or non-repudiation fields like commenter, record_creator, comment-record/bookmark relationship, it would be nice to keep them as separate tables.

**Comment by VictorAZ12** [comment]
A car-year table needs to be added to store available cars, and used as a drop-down in the frontend page
